string a = "hello";
string b = " world";
Console.Write("переменная");
double q = Convert.ToDouble(Console.ReadLine());
double e = q + q;
double t = q - q;
double s = q * q;
double f = q / q;
Console.Write("имя ");
string? name = Console.ReadLine();
Console.Write("фамилия ");
string? sur = Console.ReadLine();
Console.Write("отчество");
string? fath = Console.ReadLine();
double ph = 100;
double pd = 60;
double pdef = 40;
double mh = 200;
double md = 25;
double mdef = 10;
double ppower = pd / mdef;
double mpower = pdef / md;
double phealth = ph - mpower;
double mhealth = mh - ppower;
Console.WriteLine(a + b);
Console.WriteLine(f);
Console.WriteLine(s);
Console.WriteLine(t);
Console.WriteLine(e);
Console.WriteLine(name);
Console.WriteLine(sur);
Console.WriteLine(fath);
Console.WriteLine($"здорвье героя {ph} урон героя {pd} защта героя {pdef}");
Console.WriteLine($"здорвье монстра {mh} урон монстра {md} защта монстра {mdef}");
Console.WriteLine("итог");
Console.WriteLine($"герой осталось хп{phealth} ");
    Console.WriteLine($"монстр осталось хп {mhealth}");

